### ISSUE TITLE
Can't change the formatting of text copied

### ISSUE THREAD

**Issue by ducnguyenhuy** [spree-contrib/spree_editor#109]
With any browser...

- Copy text from google doc that has been bolded 
- Paste it into FCKeditor
- Select all text
- Try to unbold the text. You can't.

I think this is error from CKeditor because I found this https://dev.ckeditor.com/ticket/217. I don't sure which's ckeditor version that this lib is using or it's merged that fix or NOT.

Please suggest me how to fix this.

Thanks.

**Comment by alepore** [comment]
that ticket is 9 years old and about another products (FCKeditor).
this gem just integrate https://github.com/galetahub/ckeditor with spree, ckeditor issue tracker is here: https://dev.ckeditor.com/

**Comment by ducnguyenhuy** [comment]
Could you let me know which's FCK editor that this gem's using?

Thanks.

**Comment by alepore** [comment]
see the gem version here https://github.com/spree-contrib/spree_editor/blob/3-0-stable/spree_editor.gemspec#L24 (adjust for your branch) and check the actual CKeditor version here https://github.com/galetahub/ckeditor/blob/master/CHANGES.md

**Comment by ducnguyenhuy** [comment]
I see CK editor new version have fixed a few errors http://ckeditor.com/whatsnew. Could you tell me how to update CK editor version in this gem?
