### ISSUE TITLE
Generator not working in latest spree version

### ISSUE THREAD

**Issue by TechDendron** [spree-contrib/spree_editor#154]
Looks like with the latest spree version `4.11.1` the generator is failed to load.

<img width="1783" alt="Screenshot 2020-10-16 at 10 09 22 PM" src="https://user-images.githubusercontent.com/64126748/96285226-447ab600-0ffc-11eb-92cb-4bb386c5472e.png">

**Comment by nnande** [comment]
Hey @TechDendron,
I was unable to reproduce with the setup that you've mentioned. Here's is a fragment of Gemfile with the relevant spree setup used:


```
Gemfile
...
ruby '2.7.2'
...
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
...
# Spree gems
gem 'spree',                    '4.1.11 '
gem 'spree_analytics_trackers', '2.0.0'
gem 'spree_auth_devise',        '4.2.0'
gem 'spree_braintree_vzero',    '3.5.1'
gem 'spree_editor',             '0.70.0'
gem 'spree_extension',          '0.0.9'
gem 'spree_gateway',            '3.8.0'
```

Can you please make sure that:
- `spree_editor` gem is declared explicitly within your application's Gemfile?
- `bundle exec rails g spree:install` was called first?
