### ISSUE TITLE
ckeditor load before jQuery

### ISSUE THREAD

**Issue by babrovka** [spree-contrib/spree_editor#40]
ckeditor load before jQuery, it causes broblem

$(function() {
Uncaught ReferenceError: $ is not defined
    var ids = ['product_description', 'page_body'];
    for(var key in ids){
      if($('#' + ids[key]).length > 0){
        CKEDITOR.replace(ids[key]);
      }
    }
  });

and CKeditor doesnt load

**Comment by emilkarl** [comment]
I've got the same problem with 1-3-stable. Anyone solution for this?
