### ISSUE TITLE
CKEditor's buttons don't appear in production (heroku)

### ISSUE THREAD

**Issue by adoptanoob** [spree-contrib/spree_editor#95]
spree_editor works fine in development, but I have a strange behaviour in production (cedar stack Heroku, Puma server)

![capture d ecran de 2015-02-05 14 31 33](https://cloud.githubusercontent.com/assets/7680079/6061300/d23663aa-ad46-11e4-9bce-d0edf865429e.png)

Using spree 2.3.3 / Rails 4.1.6, ubuntu 14.04
my Gemfile : https://gist.github.com/adoptanoob/25158098aa58796b3ca9

**Comment by paulhuisman** [comment]
Hey, i had this problem too.

The solution provided in this post fixed it: http://stackoverflow.com/questions/19777316/problems-with-ckeditor-running-on-production-rails-application-with-heroku

**Comment by adoptanoob** [comment]
Well, I tried it with config.assets.compile = true but it then Heroku returns a Memory Quota Exceeded error since the app needs > 512Mo of Ram after that tweak. Did you encounter the same problem?

Thanks for your hint!

**Comment by adoptanoob** [comment]
Not resolved but closing it anyway.
