### ISSUE TITLE
extension not compatible with latest version of spree - 3.1.0.beta

### ISSUE THREAD

**Issue by RaVbaker** [spree-contrib/spree_editor#97]
I just tried to upgrade my shop to latest spree version but `spree_editor` said no:

    Bundler could not find compatible versions for gem "spree_backend":
      In Gemfile:
        spree_editor (>= 0) ruby depends on
          spree_backend (~> 3.0.0.beta) ruby
    
        spree (>= 0) ruby depends on
          spree_backend (3.1.0.beta)```

It's strictly fixed to `spree_backend 3.0.0.beta` when **3.1.0.beta** is already there.

**Comment by peterberkenbosch** [comment]
This has been fixed now. Thanks for reporting @RaVbaker

**Comment by RaVbaker** [comment]
Thanks @peterberkenbosch that's was fast.

**Comment by chucobo124** [comment]
Hello ! I got this error again.
Bundler could not find compatible versions for gem "spree_backend":
  In Gemfile:
    spree_editor (>= 0) ruby depends on
      spree_backend (~> 3.1.0.beta) ruby
Could not find gem 'spree_backend (~> 3.1.0.beta) ruby', which is required by gem 'spree_editor (>= 0) ruby', in any of the sources.
